# Generated by Django 5.2.15 on 2026-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('teorica', 'Teórica'), ('tecnica', 'Técnica'), ('mixta', 'Mixta')], max_length=30)),
                ('area', models.CharField(choices=[('programacion', 'Programación'), ('negocio', 'Negocio'), ('juridica', 'Jurídica')], max_length=30)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=30)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('puntaje_maximo', models.PositiveIntegerField(default=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva'), ('archivada', 'Archivada')], default='borrador', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PruebaEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('inactiva', 'Inactiva'), ('cancelada', 'Cancelada')], default='asignada', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prueba de entrevista',
                'verbose_name_plural': 'Pruebas de entrevista',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
