# Generated by Django 5.2.14 on 2026-05-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrevistas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('teorica', 'Teórica'), ('tecnica', 'Técnica'), ('mixta', 'Mixta')], max_length=30)),
                ('area', models.CharField(choices=[('programacion', 'Programación'), ('negocio', 'Negocio'), ('juridica', 'Jurídica')], max_length=30)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=30)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('puntaje_maximo', models.PositiveIntegerField(default=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva'), ('archivada', 'Archivada')], default='borrador', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_creadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PruebaEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('inactiva', 'Inactiva'), ('cancelada', 'Cancelada')], default='asignada', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_entrevista_asignadas', to='usuarios.usuario')),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_asignadas', to='entrevistas.entrevista')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas_asignadas', to='pruebas.prueba')),
            ],
            options={
                'verbose_name': 'Prueba de entrevista',
                'verbose_name_plural': 'Pruebas de entrevista',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('entrevista', 'prueba'), name='prueba_unica_por_entrevista')],
            },
        ),
    ]
