# Generated by Django 5.2.15 on 2026-06-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrevistas', '0002_initial'),
        ('pruebas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebaentrevista',
            name='asignada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_entrevista_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pruebaentrevista',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_asignadas', to='entrevistas.entrevista'),
        ),
        migrations.AddField(
            model_name='pruebaentrevista',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas_asignadas', to='pruebas.prueba'),
        ),
        migrations.AddConstraint(
            model_name='pruebaentrevista',
            constraint=models.UniqueConstraint(fields=('entrevista', 'prueba'), name='prueba_unica_por_entrevista'),
        ),
    ]
