# Generated by Django 5.2.15 on 2026-06-16 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('formato', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero / Falso'), ('abierta', 'Respuesta abierta'), ('codigo', 'Código')], max_length=30)),
                ('puntaje', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('rubrica', models.JSONField(blank=True, help_text='Criterios para calificar preguntas abiertas (usado por la IA).', null=True)),
                ('lenguaje', models.CharField(blank=True, help_text='Lenguaje para preguntas de código (ej: python).', max_length=50, null=True)),
                ('casos_prueba', models.JSONField(blank=True, help_text="Casos para código: [{'entrada': ..., 'salida_esperada': ...}].", null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['seccion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='pruebas.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='General', max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('peso_porcentual', models.PositiveIntegerField(default=100, help_text='Peso de la sección en la nota final (0-100).')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='pruebas.prueba')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['prueba', 'orden'],
                'unique_together': {('prueba', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='pruebas.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('seccion', 'orden')},
        ),
    ]
