# Generated by Django 5.2.15 on 2026-06-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_pregunta_opcion_seccion_pregunta_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='reutilizable',
            field=models.BooleanField(default=True, help_text='Si la prueba puede reutilizarse en múltiples convocatorias.'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='tipo',
            field=models.CharField(choices=[('teorica', 'Teórica'), ('practica', 'Práctica')], default='teorica', help_text='Naturaleza de la sección: teórica o práctica.', max_length=20),
        ),
    ]
