# Generated by Django 5.2.15 on 2026-06-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_prueba_reutilizable_seccion_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PruebaEntrevista',
        ),
    ]
