# Generated by Django 5.2.15 on 2026-06-18 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_delete_pruebaentrevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='peso_porcentual',
            field=models.PositiveIntegerField(default=100, help_text='Peso de la sección en la nota final (0-100).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
