# Generated by Django 5.2.15 on 2026-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=100)),
                ('severidad', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('evidencia_json', models.JSONField(blank=True, null=True)),
                ('origen', models.CharField(max_length=100)),
                ('timestamp_alerta', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
