# Generated by Django 5.2.15 on 2026-06-16 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('entrevistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='entrevistas.entrevista'),
        ),
    ]
