# Generated by Django 5.2.15 on 2026-06-17 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_initial'),
        ('sesiones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión donde se generó la alerta (Capa 3).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='sesiones.sesion'),
        ),
    ]
