# Generated by Django 5.2.15 on 2026-06-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_alerta_sesion'),
        ('entrevistas', '0005_entrevista_prueba'),
        ('sesiones', '0005_registroauditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='participante',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='entrevista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='entrevistas.entrevista'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión donde se generó la alerta (el hub del proctoring).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='sesiones.sesion'),
        ),
    ]
