# Generated by Django 5.2.14 on 2026-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('invitado', 'Invitado')], max_length=30),
        ),
    ]
