# Generated by Django 5.2.15 on 2026-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('reclutador', 'Reclutador'), ('evaluador', 'Evaluador')], default='evaluador', max_length=30),
        ),
    ]
