# Generated by Django 5.2.15 on 2026-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token de Firebase Cloud Messaging del dispositivo móvil (push).', max_length=255, null=True),
        ),
    ]
