# Generated by Django 5.2.15 on 2026-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=30)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Duración de la entrevista en minutos')),
                ('area_entrevista', models.CharField(blank=True, help_text='Área o departamento (ej: Ingeniería de Software - Backend)', max_length=200, null=True)),
                ('tipo_prueba', models.CharField(blank=True, choices=[('teorica', 'Teórica'), ('practica', 'Práctica'), ('mixta', 'Mixta')], help_text='Tipo de evaluación', max_length=20, null=True)),
                ('porcentaje_teorica', models.PositiveIntegerField(default=0, help_text='Porcentaje de preguntas teóricas (0-100). Asignado por IA')),
                ('porcentaje_practica', models.PositiveIntegerField(default=0, help_text='Porcentaje de ejercicios prácticos (0-100). Asignado por IA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre de la etapa (ej: Introducción, Preguntas Técnicas, Ejercicio Práctico)', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la etapa', null=True)),
                ('orden', models.PositiveIntegerField(help_text='Orden de aparición (1, 2, 3, ...)')),
                ('duracion_estimada_minutos', models.PositiveIntegerField(default=15, help_text='Tiempo estimado en minutos para completar esta etapa')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada')], default='pendiente', help_text='Estado actual de la etapa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Cuándo comenzó esta etapa', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Cuándo finalizó esta etapa', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['entrevista', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('invitado', 'Invitado')], default='invitado', max_length=30)),
                ('link_token', models.CharField(blank=True, help_text='JWT token para generar link', max_length=500, null=True)),
                ('link_invitacion', models.URLField(blank=True, help_text='URL completa de invitación', max_length=2000, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=30)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['fecha_invitacion'],
            },
        ),
    ]
