# Generated by Django 5.2.14 on 2026-05-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración de la entrevista en minutos'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas_evaluadas', to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('invitado', 'Invitado')], default='invitado', max_length=30)),
                ('link_token', models.CharField(blank=True, help_text='JWT token para generar link', max_length=500, null=True)),
                ('link_invitacion', models.URLField(blank=True, help_text='URL completa de invitación', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=30)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='entrevistas.entrevista')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['fecha_invitacion'],
                'unique_together': {('entrevista', 'email')},
            },
        ),
    ]
