# Generated by Django 5.2.15 on 2026-06-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrevistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas_evaluadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etapa',
            name='entrevista',
            field=models.ForeignKey(help_text='Entrevista a la que pertenece esta etapa', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='entrevistas.entrevista'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='entrevistas.entrevista'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('entrevista', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='invitado',
            unique_together={('entrevista', 'email')},
        ),
    ]
