# Generated by Django 5.2.15 on 2026-06-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
        ('entrevistas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='candidato',
            field=models.ForeignKey(blank=True, help_text='Identidad reutilizable del candidato (Módulo 1/3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones', to='candidatos.candidato'),
        ),
    ]
