# Generated by Django 5.2.14 on 2026-05-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0002_entrevista_duracion_minutos_entrevista_evaluador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='area_entrevista',
            field=models.CharField(blank=True, help_text='Área o departamento (ej: Ingeniería de Software - Backend)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='porcentaje_practica',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de ejercicios prácticos (0-100). Asignado por IA'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='porcentaje_teorica',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de preguntas teóricas (0-100). Asignado por IA'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='tipo_prueba',
            field=models.CharField(blank=True, choices=[('teorica', 'Teórica'), ('practica', 'Práctica'), ('mixta', 'Mixta')], help_text='Tipo de evaluación', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre de la etapa (ej: Introducción, Preguntas Técnicas, Ejercicio Práctico)', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la etapa', null=True)),
                ('orden', models.PositiveIntegerField(help_text='Orden de aparición (1, 2, 3, ...)')),
                ('duracion_estimada_minutos', models.PositiveIntegerField(default=15, help_text='Tiempo estimado en minutos para completar esta etapa')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada')], default='pendiente', help_text='Estado actual de la etapa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Cuándo comenzó esta etapa', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Cuándo finalizó esta etapa', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entrevista', models.ForeignKey(help_text='Entrevista a la que pertenece esta etapa', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='entrevistas.entrevista')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['entrevista', 'orden'],
                'unique_together': {('entrevista', 'orden')},
            },
        ),
    ]
