# Generated by Django 5.2.15 on 2026-06-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0003_invitado_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='area_entrevista',
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='porcentaje_practica',
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='porcentaje_teorica',
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='tipo_prueba',
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
    ]
