# Generated by Django 5.2.15 on 2026-06-16 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0004_remove_entrevista_area_entrevista_and_more'),
        ('pruebas', '0004_prueba_reutilizable_seccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='prueba',
            field=models.ForeignKey(blank=True, help_text='Prueba (plantilla del banco) que se rinde en esta convocatoria.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocatorias', to='pruebas.prueba'),
        ),
    ]
