# Generated by Django 5.2.15 on 2026-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0005_entrevista_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Override OPCIONAL de la duración. Si está vacío, se usa la duración de la prueba (fuente de verdad). Solo se llena para dar más/menos tiempo a esta convocatoria en particular.', null=True),
        ),
    ]
