# Generated by Django 5.2.15 on 2026-06-16 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrevistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('resumen_general', models.TextField(blank=True, null=True)),
                ('resumen_participante', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('puntaje_atencion', models.IntegerField(default=100)),
                ('puntaje_sospecha', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='entrevistas.entrevista')),
            ],
        ),
    ]
