# Generated by Django 5.2.15 on 2026-06-20 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
        ('sesiones', '0007_sesion_motivo_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='entrevista',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='participante',
        ),
        migrations.AddField(
            model_name='reporte',
            name='decision',
            field=models.CharField(choices=[('pendiente', 'Pendiente de decisión'), ('apto', 'Apto'), ('no_apto', 'No apto')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='firmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_firmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de la nota de la sesión al generar el informe (puede ser null si aún no se calificó).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='observaciones_evaluador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='sesion',
            field=models.OneToOneField(blank=True, help_text='Informe 1:1 de la sesión (el hub de toda la evaluación).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='sesiones.sesion'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='total_alertas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nivel_riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', help_text='Riesgo CALCULADO de las alertas del proctoring (no se recibe del front).', max_length=20),
        ),
    ]
