# Generated by Django 5.2.14 on 2026-05-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='observaciones_internas',
            field=models.TextField(blank=True, help_text='Observaciones internas del evaluador', null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa (preparación)'), ('iniciada', 'Iniciada (en curso)'), ('finalizada', 'Finalizada')], default='activa', max_length=20),
        ),
    ]
