# Generated by Django 5.2.15 on 2026-06-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrevistas', '0002_initial'),
        ('sesiones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesion',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='entrevistas.entrevista'),
        ),
    ]
