# Generated by Django 5.2.15 on 2026-06-17 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0005_entrevista_prueba'),
        ('pruebas', '0004_prueba_reutilizable_seccion_tipo'),
        ('sesiones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='grabacion_url',
            field=models.URLField(blank=True, help_text='URL de la grabación de la sesión (webhook de Jitsi).', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='identidad_verificada',
            field=models.BooleanField(default=False, help_text='True cuando el candidato pasa la verificación de identidad.'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='invitacion',
            field=models.ForeignKey(blank=True, help_text='Invitación del candidato (1 sesión por invitación). Capa 3.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='entrevistas.invitado'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_texto', models.TextField(blank=True, help_text='Respuesta del candidato: texto, opción elegida o código.', null=True)),
                ('contenido_url', models.URLField(blank=True, help_text='Si el candidato sube un archivo.', max_length=2000, null=True)),
                ('casos_pasados', models.PositiveIntegerField(blank=True, help_text='Para código: cuántos casos de prueba pasó (Judge0).', null=True)),
                ('tiempo_segundos', models.PositiveIntegerField(blank=True, help_text='Tiempo (seg) entre ver la pregunta y responder.', null=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='pruebas.pregunta')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sesiones.sesion')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['sesion', 'pregunta'],
                'unique_together': {('sesion', 'pregunta')},
            },
        ),
    ]
