# Generated by Django 5.2.15 on 2026-06-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0003_sesion_grabacion_url_sesion_identidad_verificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='feedback_ia',
            field=models.TextField(blank=True, help_text='Justificación de la IA al calificar.', null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntaje_humano',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje final del evaluador (prevalece sobre el de IA).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntaje_ia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje sugerido automático (objetivas / Judge0 / IA).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado_correccion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('corregida', 'Corregida')], default='pendiente', help_text='Estado de la corrección de las respuestas (Capa 4).', max_length=20),
        ),
        migrations.AddField(
            model_name='sesion',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota final 0-100 (ponderada por sección). Capa 4.', max_digits=5, null=True),
        ),
    ]
