# Generated by Django 5.2.15 on 2026-06-17 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0004_respuesta_feedback_ia_respuesta_puntaje_humano_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text="Etiqueta legible del actor (ej: 'candidato: a@x.com', 'sistema').", max_length=200)),
                ('accion', models.CharField(help_text='Ej: sesion_iniciada, puntaje_manual.', max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='sesiones.sesion')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario del sistema que ejecutó la acción (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
