# Generated by Django 5.2.15 on 2026-06-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0005_entrevista_prueba'),
        ('sesiones', '0005_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='invitacion',
            field=models.ForeignKey(blank=True, help_text='Invitación del candidato (1 sesión por invitación, única). Capa 3.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='entrevistas.invitado', unique=True),
        ),
    ]
