# Generated by Django 5.2.15 on 2026-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0006_alter_sesion_invitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('entregada', 'Entregada por el candidato'), ('vencida', 'Vencida por tiempo'), ('terminada', 'Terminada por el supervisor')], help_text='Cómo terminó la sesión: entregada / vencida / terminada (para el Informe).', max_length=20, null=True),
        ),
    ]
